use_frameworks!

platform :ios, '8.0'

target 'PMSpecialKit_Category_Example' do
  pod 'PMSpecialKit_Category', :path => '../'

  target 'PMSpecialKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
